version: '3.9'
services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=emergency_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    restart: always
    ports:
      - '5432:5432'