spring:
  application:
    name: emergency-management
  threads:
    virtual:
      enabled: true
  output:
    ansi:
      enabled: always
  docker:
    compose:
      lifecycle-management: start_only
  jpa:
    show-sql: true

logging:
  level:
    sa:
      sahab:
        app: TRACE