spring:
  application:
    name: emergency-management
  threads:
    virtual:
      enabled: true
  output:
    ansi:
      enabled: always
  docker:
    compose:
      lifecycle-management: start_only
  jpa:
    show-sql: true
  flyway:
    locations: classpath:db/migration/{vendor}

logging:
  level:
    sa:
      sahab:
        app: TRACE