spring:
  profiles:
    active: @mainActiveProfile@
  application:
    name: emergency-management
  threads:
    virtual:
      enabled: true
  output:
    ansi:
      enabled: always
  docker:
    compose:
      profiles:
        active: @mainActiveProfile@
      lifecycle-management: start_only
  jpa:
    show-sql: true
  flyway:
    locations:
      - classpath:db/migration/{vendor}
      - classpath:db/migration/{vendor}/@mainActiveProfile@

logging:
  level:
    sa:
      sahab:
        app: TRACE